### Books
GET http://localhost:8000/api/book

### create a product
POST http://localhost:8000/api/book
Content-Type: application/json

{
    "isbn" : "19088235",
    "title" : "Nadya Mystery",
    "author" : "648215beb7417ea31cb4c4be",
    "genre" : "6481df119677bedf3b1719a7",
    "description" : "coming soon...",
    "image" : "https://images-eu.ssl-images-amazon.com/images/I/71g2ednj0JL._AC_UL300_SR300,200_.jpg"
}

### update a product
PATCH http://localhost:8000/api/book/19088233
Content-Type: application/json

{
    "author" : "adrian2"
}

### get a product by id
GET http://localhost:8000/api/book/19088234

### delete a product by id
DELETE http://localhost:8000/api/book/19088237


### Genres

### Get genres
GET  http://localhost:8000/api/genre/

### Delete genres
DELETE  http://localhost:8000/api/genre/6481e2c357870d93c31830d9
Content-Type: application/json
    
{
    "genre": "Adrian2"
}


### post genres
POST http://localhost:8000/api/genre
Content-Type: application/json

{
  "genre": "Goblok"
}


### Author
POST http://localhost:8000/api/author
Content-Type: application/json

{
  "name": "Nadya"
}


### Author Books
GET http://localhost:8000/api/author/books?Author=Adrian

## USERS

### get user
GET http://localhost:8000/api/user

### create user
POST http://localhost:8000/api/user
Content-Type: application/json

{
    "userid": "1",
    "name" : "Adrian",
    "email" : "adrianbadjideh01@gmail.com",
    "password": "adrian1"
}

### update user
PATCH http://localhost:8000/api/user/1
Content-Type: application/json

{
    "name" : "Adrian2"
}

### delete user
DELETE http://localhost:8000/api/user/1
Content-Type: application/json


### get loan
GET http://localhost:8000/api/loan

### create loan
POST http://localhost:8000/api/loan
Content-Type: application/json

{
    "userid": "648212f1f41b975c98e3c452",
    "isbn" : "648212f1f41b975c98e3c452"
}

### delete loan
DELETE http://localhost:8000/api/loan/648388d05607a19e533eeaea